# Neural Networks

Empezamos como siempre cargando las librerias.

In [28]:
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Perceptron
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.neural_network import MLPClassifier

import numpy as np

Vamos a cargar ahora los datos y ha visualizarlos>

In [3]:
iris = datasets.load_iris()

X = iris.data
y = iris.target

print(y[:5])
print()
print(X[:5])

Generemos ahora los datos de entreno y test:

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)



Vamos ahora a preprocesar los datos de entrada:

In [8]:
sc = StandardScaler()
sc.fit(X_train)

X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)


## Perceptron
Una vez preprocesado, vamos a entrenar al perceptron:

In [26]:
nn = Perceptron(max_iter=1000, eta0=0.1, random_state=0)
nn.fit(X_train_std, y_train)
y_pred = nn.predict(X_test_std)
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.82
[[13  0  0]
 [ 0 17  0]
 [ 0  8  7]]


## Stochastic Gradient Descent

In [25]:
nn2 = SGDClassifier(loss="perceptron", eta0=0.1, learning_rate="constant", penalty=None)
nn2.fit(X_train_std, y_train)
y_pred2 = nn2.predict(X_test_std)
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred2))
print(confusion_matrix(y_test, y_pred2))

Accuracy: 0.93
[[13  0  0]
 [ 1 15  1]
 [ 0  1 14]]


## MultiLayer Perceptron

In [31]:
nn3 = MLPClassifier(random_state=1, max_iter=500)
nn3.fit(X_train_std, y_train)
y_pred3 = nn3.predict(X_test_std)
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred3))
print(confusion_matrix(y_test, y_pred3))

Accuracy: 0.98
[[13  0  0]
 [ 0 17  0]
 [ 0  1 14]]
